Install Guide
spectrocloud-labs/validator pull request #106
Opened 2023-11-14 23:25 UTC by karl-cardenas-coding

This PR adds an install guide to help newer users. The creation of `docs` folder is also added to help the maintainer team add more documentation down the road.

2023-11-15 21:07 UTC, TylerGillson commented on docs/tutorial.md
> +> You can use a different policy, but ensure that the policy has the required permissions to check the resources required by the plugin. Refer to the AWS plugin documentation for more details.
"has the required permissions to check" -> "has the permissions required to check"

2023-11-15 21:07 UTC, TylerGillson commented on docs/tutorial.md
> +Use a text editor to edit the **values.yaml** file and change navigate down to the `plugins` section and locate the `AWS` plugin.
"and change navigate down" -> ", navigate down"

2023-11-15 21:07 UTC, TylerGillson commented on docs/tutorial.md
> +secret:
L94-101 need to be indented

2023-11-15 21:07 UTC, TylerGillson commented on docs/tutorial.md
> +> Check ou the AWS [config samples](https://github.com/spectrocloud-labs/validator-plugin-aws/tree/main/config/samples) directory for more examples.
"Check ou the" -> "Check out the"

2023-11-15 21:07 UTC, TylerGillson commented on docs/tutorial.md
> +Review the contents of the `validation.yaml` file. The file contains the configuration for the validation. The `spec` section contains the configuration for the validation.  Change the `spec` section
Delete "The file contains the configuration for the validation." ?

2023-11-15 21:07 UTC, TylerGillson commented on docs/tutorial.md
> +If the validation fails, you can review the `Failures` section of the `Conditions` section to determine the cause of the failure. In this example, the IAM role is missing the required permissions. Yo
"of the `Conditions` section to" -> "of each `Condition` in its `Status` to"

2023-11-15 21:07 UTC, TylerGillson commented on docs/tutorial.md
> +If the validation fails, you can review the `Failures` section of the `Conditions` section to determine the cause of the failure. In this example, the IAM role is missing the required permissions. Yo
"and rerun the validation" -> "and wait 30s for the validation to be revalidated"

2023-11-15 21:07 UTC, TylerGillson commented on docs/tutorial.md
> +The validation results are hashed and result events are only updated if the result has changed. In this example, the validation check was successful and the `ValidationResult` CR was updated with the
"result events are only updated" -> "result events are only emitted"

A brief intro to sinks would be helpful before this sentence. The ValidationResult CRs are always updated with whatever the latest details are. But the validation controller will only re-emit events to your configured sink if the hash changes.

2023-11-16 20:53 UTC, lennessyy approved these changes

2023-11-16 20:53 UTC, lennessyy commented on docs/tutorial.md
> +The Validator will continouslly re-issue a validation cand update the `ValidationResult` CR with the result of the validation. You can use the following command to get the status of the validation. O
```suggestion
The Validator will continouslly re-issue a validation and update the `ValidationResult` CR with the result of the validation. You can use the following command to get the status of the validation. Once you addressed the cause of the failure, the validation will pass.
```

2023-11-16 20:53 UTC, lennessyy commented on docs/tutorial.md
> +To delete the Validator installation, use the following command. This command will delete the Validator and all deployed resources including the `ValidationResult` CRs.
```suggestion
To delete the Validator installation, use the following command. This command deletes the Validator and all deployed resources including the `ValidationResult` CRs.
```

2023-11-16 21:03 UTC, TylerGillson commented on docs/tutorial.md
> +The Validator will continouslly re-issue a validation cand update the `ValidationResult` CR with the result of the validation. You can use the following command to get the status of the validation. O
Once you've addressed ?

2023-11-16 21:12 UTC, karl-cardenas-coding commented
@TylerGillson ready for your re-review. All feedback has been incorporated 😄

2023-11-20 19:59 UTC, TylerGillson requested changes
Everything looks great, except for the AWS plugin auth configuration. That config changed last week due to a security issue that we identified.

2023-11-22 14:17 UTC, TylerGillson approved these changes

2023-11-22 14:17 UTC, merged