PLT-849: WIP Kubescape Plugin
spectrocloud-labs/validator pull request #244
Opened 2024-04-07 22:31 UTC by wcrum

2024-04-08 14:58 UTC, TylerGillson requested changes

2024-04-08 16:01 UTC, wcrum commented on chart/validator/values.yaml
> +          repository: quay.io/spectrocloud-labs/validator-plugin-oci
fixed.

2024-04-08 17:42 UTC, ahmad-ibra requested changes
@wcrum are you able to address the vulnerability reported in this PR. It should be as simple as running `go get -u golang.org/x/net`

2024-04-08 18:00 UTC, ahmad-ibra reviewed
@wcrum are you able to confirm if the kubescape plugin will require any secrets? If it does, please set up the secret configuration in the `pluginSecrets` section at the bottom of the `chart/validator/values.yaml`

2024-04-08 18:07 UTC, wcrum commented
> @wcrum are you able to confirm if the kubescape plugin will require any secrets? If it does, please set up the secret configuration in the `pluginSecrets` section at the bottom of the `chart/validator/values.yaml`

Kubescape plugin does not require any secrets as of right now, Kubescape itself does not have any secrets either.

2024-04-08 20:05 UTC, ahmad-ibra approved these changes
LGTM, thanks for getting this in!

2024-04-22 17:43 UTC, TylerGillson approved these changes

2024-05-13 20:12 UTC, merged